spring:
  application:
    name: processor-csv
  #fichero a cargar
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always
    user:
      file-path: ./data/users.csv

  datasource:
    url: jdbc:postgresql://localhost:5432/csv_db
    username: #username
    password: #password
    driver-class-name: org.postgresql.Driver
   # una vez ejecutado cambiar de create a update 
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  #uso de quartz para programar los job
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
#procesador csv
logging:
  level:
    root: INFO
    org:
      springframework=ERROR:
    com.processor_csv: DEBUG
    file:
      name=logs/processor-csv:
        log:
